import { getSession } from 'next-auth/react';
import Head from 'next/head';
import Auth from '../../components/Auth';

function AuthType({ authType }) {
	const pageTitle = authType.charAt(0).toUpperCase() + authType.slice(1);

	return (
		<>
			<Head>
				<title>{pageTitle}</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className="container mx-auto w-[340px] md:w-full lg:w-full">
				{authType === 'login' ? (
					<Auth login="login" />
				) : (
					<Auth register="register" />
				)}
			</div>
		</>
	);
}

export default AuthType;

export const getServerSideProps = async (context) => {
	const { req } = context;

	const session = await getSession({ req });

	if (session) {
		return {
			redirect: { destination: '/products' }
		};
	}

	return {
		props: {
			authType: context.query.authType
		}
	};
};
