import Head from 'next/head';
import Auth from '../../components/Auth';

function AuthType({ authType }) {
	return (
		<>
			<Head>
				<title>{authType}</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className="container mx-auto w-[340px] md:w-full lg:w-full">
				{authType === 'login' ? (
					<Auth login="login" />
				) : (
					<Auth register="register" />
				)}
			</div>
		</>
	);
}

export default AuthType;

export const getStaticProps = async ({ params }) => {
	const { authType } = params;

	return {
		props: {
			authType
		},
		revalidate: 10
	};
};

export const getStaticPaths = () => {
	return {
		paths: [],
		fallback: 'blocking'
	};
};
