import Head from 'next/head';
import Image from 'next/image';
import Dashboard from '../components/Dashboard';
import Dashboard2 from '../components/Dashboard2';
import Dashboard3 from '../components/Dashboard3';
import Products from '../components/Products';

function dashboard() {
	return (
		<>
			<Head>
				<title>Dashboard</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			{/* <div className="container mx-auto">
				<p className="text-4xl text-center font-bold mt-20">Dashboard</p>
			</div> */}

			<Products />
		</>
	);
}

export default dashboard;
