import Head from 'next/head';
import Image from 'next/image';
import SignIn from '../components/SignIn';
import styles from '../styles/Home.module.css';

export default function Home() {
	return (
		<div>
			<Head>
				<title>Log in</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className="container mx-auto w-[340px] md:w-full lg:w-full">
				{/* <p className="text-3xl">Mighty Jaxx Dashboard</p> */}
				<SignIn />
			</div>
		</div>
	);
}
