import { getSession } from 'next-auth/react';
import Head from 'next/head';
import Image from 'next/image';
import WelcomePage from '../components/WelcomePage';

export default function Home({ auth }) {
	return (
		<>
			<Head>
				<title>Welcome</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<WelcomePage auth={auth} />
		</>
	);
}

export const getServerSideProps = async (context) => {
	const { req } = context;
	const session = await getSession({ req });

	console.log(session);

	return {
		props: {
			auth: session
		}
	};
};
