import Head from 'next/head';
import Auth from '../components/Auth';
import SignIn from '../components/SignIn';

function Login() {
	return (
		<>
			<Head>
				<title>Register</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className="container mx-auto w-[340px] md:w-full lg:w-full">
				<Auth login="login" />
			</div>
		</>
	);
}

export default Login;
