import { getSession } from 'next-auth/react';
import Head from 'next/head';
import { useState, useEffect } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import AllProducts from '../components/AllProducts';
import {
	deleteSelectedProductsAsync,
	getProductsAsync
} from '../redux/features/productSlice';

function Products({ data }) {
	const dispatch = useDispatch();
	const products = useSelector((state) => state.products.products);
	const [allProducts, setAllProducts] = useState([]);
	const [selectedItems, setSelectedItems] = useState([]);

	useEffect(() => {
		dispatch(getProductsAsync(data?.user?.email));
	}, []);

	const handleDeleteSelected = () => {
		dispatch(deleteSelectedProductsAsync(selectedItems));
		setSelectedItems([]);
	};

	return (
		<div className="container mx-auto">
			<Head>
				<title>Dashboard</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<p className="text-2xl text-center m-5">Search Bar</p>
			{selectedItems.length > 0 && (
				<div className="text-center">
					<button
						onClick={handleDeleteSelected}
						className=" text-white justify-center align-center bg-red-700 hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300 font-medium rounded-lg text-sm md:text-md lg:text-md px-5 py-2 text-center dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-800"
					>
						Remove selected products
					</button>
				</div>
			)}
			<div className="flex flex-wrap ">
				{products.map((product, idx) => (
					<AllProducts
						key={idx}
						product={product}
						setSelectedItems={setSelectedItems}
						selectedItems={selectedItems}
					/>
				))}
			</div>
		</div>
	);
}

export default Products;

export const getServerSideProps = async (context) => {
	const { req } = context;
	const session = await getSession({ req });

	if (!session) {
		return {
			redirect: { destination: '/auth/login' }
		};
	}
	console.log(session);
	return {
		props: { data: session }
	};
};
