import { getSession, useSession } from 'next-auth/react';
import Head from 'next/head';
import { useState, useEffect } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import AllProducts from '../components/AllProducts';
import { getProductsAsync } from '../redux/features/productSlice';

function Products() {
	const dispatch = useDispatch();
	const products = useSelector((state) => state.products.products);
	const [allProducts, setAllProducts] = useState([]);

	const { data: session } = useSession();
	console.log(session);
	useEffect(() => {
		session && dispatch(getProductsAsync(session?.user?.email));
	}, [session]);

	return (
		<div className="container mx-auto">
			<Head>
				<title>Dashboard</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<p className="text-2xl text-center m-5">Search Bar</p>
			<div className="flex flex-wrap ">
				{/* {Array(4)
					.fill(0)
					.map((_, idx) => (
						<AllProducts key={idx} />
					))} */}
				{products.map((product, idx) => (
					<AllProducts key={idx} product={product} />
				))}
			</div>
		</div>
	);
}

export default Products;

export const getServerSideProps = async (context) => {
	const { req } = context;
	const session = await getSession({ req });

	console.log(session);

	// const {email, image}

	if (!session) {
		return {
			redirect: { destination: '/auth/login' }
		};
	}

	return {
		props: { data: 'products' }
	};
};
