import Head from 'next/head';
import Products from '../components/Products';

function dashboard() {
	return (
		<>
			<Head>
				<title>Dashboard</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			{/* <div className="container mx-auto">
				<p className="text-4xl text-center font-bold mt-20">Dashboard</p>
			</div> */}
			{/* <div className="container mx-auto text-center"> */}

			{Array(4)
				.fill(0)
				.map((_, idx) => (
					<div key={idx}>
						<Products />
					</div>
				))}
			{/* </div> */}
		</>
	);
}

export default dashboard;
