import React from 'react';
import Signup from '../components/Signup';
import Head from 'next/head';

function Register() {
	return (
		<>
			<Head>
				<title>Register</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className="container mx-auto w-[340px] md:w-full lg:w-full">
				<Signup />
			</div>
		</>
	);
}

export default Register;
